### ISSUE TITLE
Comma in user password causes "Prepare-BuildEnvironment" step to crash

### ISSUE THREAD

**Issue by markvanaalst** [Sitecore/Sitecore.HabitatHome.Platform#146]
A comma in a user password for dev.sitecore.net causes an error during the build step "Prepare-BuildEnvironment". Have tried to provide the credentials using scripts arguments as well as using environment variables.

Workaround: change password at: https://profile.sitecore.net/SignUp/Validation.aspx

```
Error:
Executing: &"C:/projects/Sitecore.HabitatHome.Platform/Azure/HelperScripts/Prepare-BuildEnvironment.ps1" "C:\projects\Sitecore.HabitatHome.Platform\cake-config.json" [REDACTED] [REDACTED]
An error occurred when executing task 'Prepare-BuildEnvironment'.
Error: One or more errors occurred.
        Failed to Execute Powershell Script: System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'devSitecorePassword'. Cannot convert value to type System.String. ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert value to type System.String. ---> System.Management.Automation.PSInvalidCastException: Cannot convert value to type System.String.
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
```

**Comment by jeanfrancoislarente** [comment]
Who uses a comma in a password? :)
We'll take a look, thanks for reporting!

**Comment by Zhaph** [comment]
Similar issue with `"`, `$` and the like as well.

**Comment by jeanfrancoislarente** [comment]
Thanks @Zhaph for the clarification. We'll try to address this as soon as we can.

**Comment by Zhaph** [comment]
I worked around this by manually downloading `Sitecore Azure Toolkit 2.1.0 rev. 181023.zip` into the appropriate Assets folder (in my case `Deploy\9.1.0\OnPrem\XPSingle\assets`)

**Comment by jeanfrancoislarente** [comment]
Good workaround available and no longer supporting PaaS deployments for 9.2+
