### ISSUE TITLE
Error on deploying Sitecore.HabitatHome.Platform on Sitecore 9.1.1

### ISSUE THREAD

**Issue by helhaddad** [Sitecore/Sitecore.HabitatHome.Platform#158]
Hello,

I tried to install Sitecore.HabitatHome.Platform on Sitecore 9.1.1, but I got the error message below, If anyone wants to help me please

Error message 

Completed in 8201ms.
****ERROR OCCURRED****
Cake.exe : An error occurred when executing task 'Sync-Unicorn'.
At C:\projects\Sitecore.HabitatHome.Platform\build.ps1:248 char:1
+ &$CAKE_EXE $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...'Sync-Unicorn'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error: 
One or more errors occurred.
	
Failed to Execute Powershell Script: System.Management.Automation.RuntimeException: Unicorn Sync to https://xp911.rec.sitecore/unicorn.aspx?verb=Sync&configuration=&skipTransparentConfigs=0 returned an error. See the preceding log for details. ---> System.
Management.Automation.RuntimeException: Unicorn Sync to https://xp911.rec.sitecore/unicorn.aspx?verb=Sync&configuration=&skipTransparentConfigs=0 returned an error. See the preceding log for details.
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()

**Comment by jeanfrancoislarente** [comment]
Sorry for the delay. We're going to look into this shortly. We're on-site planning at the moment.

**Comment by jeanfrancoislarente** [comment]
No longer relevant
