### ISSUE TITLE
Generate-habitatHomeUpdatePackages

### ISSUE THREAD

**Issue by jrudley** [Sitecore/Sitecore.HabitatHome.Platform#159]
I build a vm with vs2017 in Azure, follow the readme for Azure and getting an error. When I manually execute the powershell, it finishes just fine. Seems to be something with cake and a shouldcontinue prompt.

Executing: &"C:/projects/Sitecore.HabitatHome.Platform/Azure/HelperScripts/Generate-HabitatHomeUpdatePackages.ps1" "C:\p
rojects\Sitecore.HabitatHome.Platform\cake-config.json"
C:\Deploy\9.1.1\Cloud\XP\Website\HabitatHome
Creating c:\Deploy\9.1.1\Cloud\XP\assets\HabitatHome
C:\Deploy\9.1.1\Cloud\XP\assets\HabitatHome
An error occurred when executing task 'Generate-HabitatHomeUpdatePackages'.
Error: One or more errors occurred.
        Failed to Execute Powershell Script: System.Management.Automation.CmdletInvocationException: Exception calling "
ShouldContinue" with "2" argument(s): "The method or operation is not implemented." ---> System.Management.Automation.Me
thodInvocationException: Exception calling "ShouldContinue" with "2" argument(s): "The method or operation is not implem
ented." ---> System.NotImplementedException: The method or operation is not implemented.
   at Cake.Powershell.CakePSHostInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 de
faultChoice)
   at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String messag
e, Collection`1 choices, Int32 defaultChoice)
   at System.Management.Automation.MshCommandRuntime.InquireHelper(String inquireMessage, String inquireCaption, Boolean
 allowYesToAll, Boolean allowNoToAll, Boolean replaceNoWithHalt, Boolean hasSecurityImpact)
   at System.Management.Automation.MshCommandRuntime.DoShouldContinue(String query, String caption, Boolean hasSecurityI
mpact, Boolean supportsToAllOptions, Boolean& yesToAll, Boolean& noToAll)
   at System.Management.Automation.MshCommandRuntime.ShouldContinue(String query, String caption)
   at System.Management.Automation.Cmdlet.ShouldContinue(String query, String caption)
   at CallSite.Target(Closure , CallSite , PSScriptCmdlet , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exc
eption)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProces
s)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exc
eption)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object in
putToProcess)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
PS C:\projects\Sitecore.HabitatHome.Platform>

**Comment by jrudley** [comment]
to note, if I edit the build.cake file and hard code the path to that function, it works just fine. I can repo this each time.

**Comment by jeanfrancoislarente** [comment]
thanks for the details!

**Comment by jrudley** [comment]
Hi,
I tried again to debug this error a bit more. This is indeed not an issue with cake, but a missing dependency for nuget. It is prompting during the cake build for nuget
![image](https://user-images.githubusercontent.com/1934411/60281437-91e48880-98ca-11e9-8e3a-ea1763f95aa3.png)

Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force fixes this issue. This could just be a dependency requirement before running the build. We can close this out and make this a dependency requirement or have cake install it during the build. Thanks

**Comment by jeanfrancoislarente** [comment]
Hello @jrudley we've decided to discontinue support for Azure PaaS in the demo codebase.
