### ISSUE TITLE
missing json file habitatHome_xConnect.json

### ISSUE THREAD

**Issue by jrudley** [Sitecore/Sitecore.HabitatHome.Platform#160]
It is missing the file habitatHome_xConnect.json. There is an xconnect.json file at C:\projects\Sitecore.HabitatHome.Platform\Azure\XP\ARM Templates\HabitatHome

An error occurred when executing task 'Azure-Upload-Packages'.
Error: One or more errors occurred.
        Failed to Execute Powershell Script: System.Management.Automation.CmdletInvocationException: Cannot bind argument to parameter 'Path' because it is an empty string. ---> System.Management.Automation.Para
meterBindingValidationException: Cannot bind argument to parameter 'Path' because it is an empty string.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\projects\Sitecore.HabitatHome.Platform\Azure\XP\ARM Templates
\HabitatHome\habitatHome_xConnect.json' because it does not exist.
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& provider
Instance)
   at System.Management.Automation.SessionStateInternal.GetItem(String[] paths, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.GetItemCommand.ProcessRecord()
PS C:\projects\Sitecore.HabitatHome.Platform>

**Comment by jeanfrancoislarente** [comment]
Hey @jrudley can you confirm which branch you're taking this from? Just want to make sure we investigate the right one!

**Comment by jrudley** [comment]
@jeanfrancoislarente Hey, thanks for the quick reply. It is the master branch

**Comment by jeanfrancoislarente** [comment]
We've been short staffed for a bit and due to the lack of interest have fallen behind a bit on the Azure PaaS deployment.

It's _likely_ going to be something that I need to wait till next week to look at.

**Comment by jrudley** [comment]
no worries. I copied the xconnect file and renamed it to what was expected and everything is working after my deploy. I will submit a PR for the other things I found, but haven't reported. I believe they are just some missing documentation on how to launch. Thanks again

**Comment by jeanfrancoislarente** [comment]
Fantastic, I appreciate the help!
I'll make sure it also gets pulled into the next version!

**Comment by jeanfrancoislarente** [comment]
Closing this issue with a valid workaround.
