### ISSUE TITLE
Duplicate serialized item IDs

### ISSUE THREAD

**Issue by JaapioNL** [Sitecore/Sitecore.HabitatHome.Platform#166]
Hi,

I just tried to deploy this site on my local machine but I get 'Duplicate serialized item IDs'  errors from unicorn sync.

`Project.Global.Website is being synced.
[S] master:/sitecore/content/Habitat Sites/Global/Presentation/Rendering Variants/Hero/Hero Double Image/Widget Wrapper (8c447fd8-b21f-400c-b8c8-86808b8b7052) by Serialization Preset Predicate but it was in Serialization File System Data Store.
This usually indicates an extraneous excluded serialized item is present in the , which should be removed.
Duplicate serialized item IDs were detected (8c447fd8-b21f-400c-b8c8-86808b8b7052) - this usually indicates corruption in the serialization provider data.
Item 1: master:/sitecore/content/Habitat Sites/Global/Presentation/Rendering Variants/Hero/Hero Double Image/Widget Wrapper (8c447fd8-b21f-400c-b8c8-86808b8b7052)
Item 1 ProviderId: D:/sc/shp/src\Project\Global\serialization\Content\66e5b6db-e51d-45c3-820a-fd55b85bd0f1\Widget Wrapper.yml
Item 2: master:/sitecore/content/Habitat SXA Sites/Global/Presentation/Rendering Variants/Hero/Hero Double Image/Widget Wrapper (8c447fd8-b21f-400c-b8c8-86808b8b7052)
Item 2 ProviderId: D:/sc/shp/src\Project\Global\serialization\Content\Habitat SXA Sites\Global\Presentation\Rendering Variants\Hero\Hero Double Image\Widget Wrapper.yml
ERROR: Consistency check failed - aborting loading. (Unicorn.Loader.ConsistencyException)
at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
at Unicorn.Loader.SerializationLoader.LoadOneLevel(IItemData rootSerializedItemData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
at Unicorn.Loader.SerializationLoader.LoadTreeInternal(IItemData root, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
at Unicorn.Loader.SerializationLoader.LoadTree(IItemData rootItemData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
at Unicorn.Loader.SerializationLoader.LoadAll(IItemData[] rootItemsData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker, Action`1 rootLoadedCallback)
at Unicorn.SerializationHelper.SyncTree(IConfiguration configuration, Action`1 rootLoadedCallback, Boolean runSyncStartPipeline, IItemData partialSyncRoot)
at Unicorn.SerializationHelper.SyncConfigurations(IConfiguration[] configurations, IProgressStatus progress, ILogger additionalLogger)`

For now I renamed the folders with a guid for a name (in \src\Project\Global\serialization\Content). Is this an error or did I miss anything in the readme?

**Comment by jflheureux** [comment]
Try the release/9.2.0 branch instead of master. Master branch seems to be broken.

**Comment by jeanfrancoislarente** [comment]
We've since pushed to master to fix this issue correct @jflheureux ?

**Comment by jflheureux** [comment]
Yes, I would be surprised if this issue is still there in the master/develop branches.
